site_name: dove
site_url: "https://jialedove.github.io/Jialedove/"
theme:
  name:  material       # 启用 Material 主题
  language: zh 
  features:
      - navigation.tabs # 把一级导航渲染成横向标签
      - navigation.indexes   # （可选）让每个 Tab 可以点击到 index.md
      - navigation.path # 路径面包屑
      - navigation.instant  
      - navigation.instant.progress
      #- toc.integrate # 标题导航目录
      - navigation.top # 顶部导航栏
      - search.highlight # 搜索高亮
  palette:
    # Palette toggle for automatic mode
    # - media: "(prefers-color-scheme)"
    #   toggle:
    #     icon: material/brightness-auto
    #     name: 切换到浅色
    - media: "(prefers-color-scheme: light)"
      scheme: white
      primary: white     # 主题色
      accent: light blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: 切换到深色
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/toggle-switch
        name: 跟随系统

markdown_extensions:
  - admonition            # 提示框
  - codehilite            # 代码高亮
  - pymdownx.tasklist     # 任务清单
plugins:
  - search                # 内置快速搜索
  - tags                  # 文章标签
extra_javascript:
  - javascripts/shortcuts.js # 快捷键脚本
extra:
  analytics:
    provider: google
    property: G-BMLP6MP942 # Google Analytics ID
  social:
    - icon: material/github
      link: https://github.com/jialedove
      name: GitHub | jialedove
nav:
  - Home: index.md
  - 知识:
      - 拳击: 
        - 拳击站姿: boxing-stance.md
  - 文章:
      - 常识，如何获得常识？: common-sense.md
  - 项目:
      - 个人网站: my-site.md
  - 标签: tags.md
