name: Publish MkDocs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:           # 让默认 token 具备写入权限
      contents: write
      pages: write
    steps:
      - uses: actions/checkout@v4          # v4 稳定版

      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install MkDocs & theme
        run: |
          pip install mkdocs mkdocs-material

      - name: Build and deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   # 供 mkdocs gh-deploy 使用
        run: |
          mkdocs gh-deploy --clean --force            # 构建并推送 gh-pages